init:
  - git config --global core.autocrlf true

environment:
  global:
    GH_REF: github.com/alanag13/alanag13.github.io.git

platform:
  - x64

branches:
  only:
    - source

cache:
  - '%USERPROFILE%\.nuget\packages -> **\packages.xml'
  - node_modules -> package.json
  - node_cache -> package.json  

install:
  - mkdir ..\Wyam
  - mkdir ..\output
  # Fetch the latest version of Wyam 
  - "curl -s https://raw.githubusercontent.com/Wyamio/Wyam/master/RELEASE -o ..\\Wyam\\wyamversion.txt"
  - set /P WYAMVERSION=< ..\Wyam\wyamversion.txt
  - echo %WYAMVERSION%
  # Get and unzip the latest version of Wyam
  - ps: Start-FileDownload "https://github.com/Wyamio/Wyam/releases/download/$env:WYAMVERSION/Wyam-$env:WYAMVERSION.zip" -FileName "..\Wyam\Wyam.zip"
  - 7z x ..\Wyam\Wyam.zip -o..\Wyam -r
  - npm install

test: off

build_script:
  - npm run-script build

on_success:
  - git config --global user.name "AppVeyor"
  - git config --global user.email "appveyor@alangrgic.com"
  - git rev-parse HEAD > _commit.txt
  - set /P CURRENT_COMMIT=< _commit.txt
  - git clone -b master "https://%GH_TOKEN%@%GH_REF%" _deploy  
  - cd _deploy
  #delete the whole site
  - git rm -rf .
  #add some github config files
  - touch .nojekyll
  - echo alangrgic.com > CNAME
  #copy the new site over
  - xcopy ..\output . /E
  - git add -A
  - git commit --allow-empty -m "Deploying site for %CURRENT_COMMIT%"
  - git push origin master